#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wednesday 20 January 2021.
Finished on
@author: h.
References:
https://projecteuler.net/about
"""
#------------------------------------------------------------------------------#
""" Question.
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

                        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""
#------------------------------------------------------------------------------#
import math

seq = []
four_million = 4000000

for i in list(range(0, four_million)):
    if i[-1] += i[-2]
    #
    # Check to see if my holding value + current value = index
        # If yes and if even append to sequence.
    print(i)






















#------------------------------------------------------------------------------#
